### ISSUE TITLE
Type Casting Issue: Accessing Marker from DragEndEvent in Rust

### ISSUE THREAD

**Issue by wildwestrom** [headless-studio/leptos-leaflet#23]
I want to update some state each time I encounter a `DragEndEvent` based on the new position of a marker.
Unfortunately, I can't figure out how to tell the Rust Compiler that I can definitely get at the marker by calling target on the event.
Is there a way to do this?

```rs
    let drag_events = {
        DragEvents::new().on_drag_end(move |ev: DragEndEvent| {
            let marker = ev.target() as Marker;
            let pt = marker.get_lat_lng();
            set_lat(pt.lat());
            set_lng(pt.lng());
        })
    };
```

**Comment by dgsantana** [comment]
Hi,
You can't just do a "as" cast as normal Rust struct. The underlying types of leaflet are javascript objects (pointers to javascripts objects). For casting to a Marker you can do as follow:
```rust
let drag_events = {
        DragEvents::new().on_drag_end(move |ev: DragEndEvent| {
            let marker = ev.target().unchecked_into<leaflet::Marker>(); // This will cast the target javascript object to a leaflet Marker.
            let pt = marker.get_lat_lng();
            set_lat(pt.lat());
            set_lng(pt.lng());
        })
    };
```

**Comment by wildwestrom** [comment]
This worked quite well for me! Thank you very much!
