### ISSUE TITLE
Removing Marker

### ISSUE THREAD

**Issue by siqpush** [headless-studio/leptos-leaflet#38]
Is it possible to remove a marker from the map based on some condition? I've banged my head a bit and my last attempt was something like the below. I am fairly sure this is not the right direction but thought it may help explain what I am trying to do. 

```
create_effect(move |_| {
        if let Some(marker) = marker.get().map(|obj: Object| obj.unchecked_into::<Marker>()) {
            let pane = marker.get_pane();
            if let Some(element) = pane
                .get_elements_by_class_name("leaflet-marker-icon leaflet-zoom-animated leaflet-interactive leaflet-marker-draggable")
                .item(0)
            {
                if some_remove_marker_signal.get() {
                    pane.remove_child(&element).expect("failed to remove marker");
                }
            }
        }
    });

     view! {
              <Marker
                  position={Position::default()}
                  layer_events=LayerEvents::new()
                  .on_add(move |ev| {
                      marker.set_untracked(Some(ev.target()));
                  })
     }
```

**Comment by otopetrik** [comment]
This seems to work:
```
view! {
    <Show when=move || { some_remove_marker_signal.get() == false }>
        <Marker position=... > ... </Marker>
    </Show>
}

**Comment by dgsantana** [comment]
That is one way (the on_cleanup on the marker removes it from the map), another is to create/destroy the marker using the leaflet API. When I get some time I will create an example.

**Comment by siqpush** [comment]
thanks @otopetrik and @dgsantana - tried the Show approach earlier on and was having trouble. Almost appears as though the once the marker is bound to the map Show no longer has the ability to remove - could be a self inflicted reactive issue though. 

I think the leaflet api approach would be super beneficial to gaining a better understanding.

**Comment by dgsantana** [comment]
@siqpush I added a very simple example that should get you started, it's [here](https://github.com/headless-studio/leptos-leaflet/blob/main/examples/leaflet-api/src/app.rs).
There is an helper struct to handle the removal of the marker in this case when the struct is dropped. But this can be applied to any other type of leaflet. I build a line and point drawing system for leaflet in rust around this idea. You can also add events using this api.

**Comment by siqpush** [comment]
@dgsantana this is awesome - gave me much better insight insight into leaflet and how your api intertwines. Also, the IntoLatLng impl was a nice cherry on top! Thanks again.
