### ISSUE TITLE
Popup offset prop uses u32 instead of i32, preventing upward offsets

### ISSUE THREAD

**Issue by geoffreygarrett** [headless-studio/leptos-leaflet#41]
The `Popup` component's `offset` prop currently uses `u32` for its coordinates:

```rust
#[prop(into, optional)] offset: Option<Signal<(u32, u32)>>
```

This prevents positioning popups above markers since negative offsets are not possible. The offset type should be changed to `i32` to allow both positive and negative offsets, which is a common use case when positioning popups relative to markers.

### Current Behavior
- Offset coordinates must be positive (`u32`)
- Cannot offset popups above their anchor points
- Forces workarounds like adjusting marker positions or anchor points

### Expected Behavior
- Offset coordinates can be positive or negative (`i32`)
- Allows natural positioning of popups above markers
- Matches typical popup positioning patterns in map UIs

### Proposed Change
```rust
#[prop(into, optional)] offset: Option<Signal<(i32, i32)>>
```

### Additional Notes
- This matches Leaflet's JavaScript API which allows negative offsets
- Similar props like `auto_pan_padding` might also benefit from using signed integers

**Comment by dgsantana** [comment]
Thank for your proposal, the change is simple but of course is a breaking change. As soon as I have some time I will make the change, and change the minor version.

**Comment by dgsantana** [comment]
Version 0.9 includes now that.
